// Package pdf implements the PDF report formatter using gofpdf.
package pdf

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
	"github.com/osv/finding-service/internal/domain/report"
	"github.com/osv/finding-service/internal/domain/report/service"
	"github.com/osv/finding-service/internal/formatters"
)

// PDFFormatter renders a structured PDF report.
type PDFFormatter struct{}

// New creates a new PDFFormatter.
func New() *PDFFormatter { return &PDFFormatter{} }

// ContentType returns application/pdf.
func (f *PDFFormatter) ContentType() string { return "application/pdf" }

// FileExtension returns ".pdf".
func (f *PDFFormatter) FileExtension() string { return ".pdf" }

// severity colors as RGB tuples
var severityColors = map[string][3]int{
	"CRITICAL": {220, 38, 38},
	"HIGH":     {234, 88, 12},
	"MEDIUM":   {217, 119, 6},
	"LOW":      {101, 163, 13},
	"UNKNOWN":  {107, 114, 128},
}

// Format renders the PDF report.
func (f *PDFFormatter) Format(_ context.Context, data report.ReportInput, _ formatters.FormatOptions) ([]byte, error) {
	pdf := gofpdf.New("L", "mm", "A4", "") // Landscape for wide tables
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)

	ts := data.GeneratedAt
	if ts.IsZero() {
		ts = time.Now()
	}

	// ── Title Page ──────────────────────────────────────────────────────────
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 22)
	pdf.SetTextColor(30, 41, 59)
	pdf.CellFormat(0, 12, "CVE Binary Tool Scan Results", "", 1, "C", false, 0, "")

	pdf.Ln(4)
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(100, 116, 139)
	pdf.CellFormat(0, 7, "Target: "+data.ScanTarget, "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 7, "Generated: "+ts.UTC().Format("2006-01-02 15:04 UTC"), "", 1, "C", false, 0, "")

	// Severity summary table
	pdf.Ln(8)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(30, 41, 59)
	pdf.CellFormat(0, 8, "Summary", "", 1, "L", false, 0, "")
	pdf.Ln(2)

	severityCounts := map[string]int{"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
	totalCVEs := 0
	for _, cves := range data.CVEData {
		for _, c := range cves {
			sev := strings.ToUpper(c.Severity)
			if _, ok := severityCounts[sev]; ok {
				severityCounts[sev]++
			}
			totalCVEs++
		}
	}

	colW := 40.0
	renderSummaryRow(pdf, "Total CVEs", fmt.Sprintf("%d", totalCVEs), [3]int{30, 41, 59}, colW)
	for _, sev := range []string{"CRITICAL", "HIGH", "MEDIUM", "LOW"} {
		renderSummaryRow(pdf, sev, fmt.Sprintf("%d", severityCounts[sev]), severityColors[sev], colW)
	}

	// ── Per-Product CVE Tables ───────────────────────────────────────────────
	for product, cves := range data.CVEData {
		filtered := service.FilterAndSort(cves, data.MinSeverity, data.MinScore)
		if len(filtered) == 0 {
			continue
		}

		pdf.AddPage()

		// Product header
		pdf.SetFont("Helvetica", "B", 13)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(248, 250, 252)
		header := fmt.Sprintf("%s / %s  %s", product.Vendor, product.Product, product.Version)
		pdf.CellFormat(0, 9, header, "", 1, "L", true, 0, "")
		pdf.Ln(2)

		// Table header
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetFillColor(241, 245, 249)
		pdf.SetTextColor(51, 65, 85)
		colWidths := []float64{45, 22, 14, 80, 14, 30}
		headers := []string{"CVE Number", "Severity", "Score", "CVSS Vector", "Exploit", "Source"}
		for i, h := range headers {
			pdf.CellFormat(colWidths[i], 7, h, "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)

		// Table rows
		pdf.SetFont("Helvetica", "", 9)
		for _, cve := range filtered {
			if pdf.GetY() > 180 {
				pdf.AddPage()
			}

			color := severityColors[strings.ToUpper(cve.Severity)]
			pdf.SetTextColor(color[0], color[1], color[2])
			pdf.CellFormat(colWidths[0], 6, cve.CVENumber, "1", 0, "L", false, 0, "")

			pdf.SetTextColor(color[0], color[1], color[2])
			pdf.CellFormat(colWidths[1], 6, cve.Severity, "1", 0, "C", false, 0, "")

			pdf.SetTextColor(51, 65, 85)
			pdf.CellFormat(colWidths[2], 6, fmt.Sprintf("%.1f", cve.Score), "1", 0, "C", false, 0, "")

			vector := cve.CVSSVector
			if len(vector) > 30 {
				vector = vector[:30] + "…"
			}
			pdf.CellFormat(colWidths[3], 6, vector, "1", 0, "L", false, 0, "")

			exploitStr := "No"
			if cve.IsExploit {
				exploitStr = "⚠ Yes"
				pdf.SetTextColor(220, 38, 38)
			}
			pdf.CellFormat(colWidths[4], 6, exploitStr, "1", 0, "C", false, 0, "")
			pdf.SetTextColor(51, 65, 85)
			pdf.CellFormat(colWidths[5], 6, cve.DataSource, "1", 0, "C", false, 0, "")
			pdf.Ln(-1)
		}
	}

	// Footer on all pages
	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(148, 163, 184)
		pdf.CellFormat(0, 5, fmt.Sprintf("Page %d | Generated by CVE Binary Tool", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("pdf formatter: %w", err)
	}
	return buf.Bytes(), nil
}

func renderSummaryRow(pdf *gofpdf.Fpdf, label, value string, color [3]int, colW float64) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(color[0], color[1], color[2])
	pdf.CellFormat(colW, 7, label, "1", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(30, 41, 59)
	pdf.CellFormat(20, 7, value, "1", 1, "C", false, 0, "")
}

// Ensure interface compliance.
var _ formatters.Formatter = (*PDFFormatter)(nil)
