root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  full_bin = "./tmp/main --config config/config.yaml"
  include_ext = ["go", "yaml", "env"]
  exclude_dir = ["tmp", "vendor", "testdata", "migrations", "specs", "build"]
  delay = 1000
  kill_delay = 500
  rerun = false

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
