// Package impl — Ecosystem parity test suite (TASK-09-01).
// Tests Go ecosystem implementations against expected Python outputs.
//
// Inline tests cover PyPI, Maven, Alpine, Go, npm.
// File-based tests load from testdata/ecosystem_parity_cases.json
// (generated by running Python tests and capturing outputs).
package impl_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// ParityTestCase represents one parity test case from the JSON file.
type ParityTestCase struct {
	Ecosystem string `json:"ecosystem"`
	Input     string `json:"input"`
	Valid      bool   `json:"valid"`
	// Optional: sort key comparison
	InputA   string `json:"input_a,omitempty"`
	InputB   string `json:"input_b,omitempty"`
	ABeforeB bool   `json:"a_before_b,omitempty"`
}

// loadParityCases loads parity cases from testdata/ecosystem_parity_cases.json.
// If the file is missing, the test is skipped.
func loadParityCases(t *testing.T) []ParityTestCase {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	dir := filepath.Dir(file)
	path := filepath.Join(dir, "testdata", "ecosystem_parity_cases.json")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("parity testdata not found at %s: %v", path, err)
		return nil
	}
	var cases []ParityTestCase
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatalf("parse parity cases: %v", err)
	}
	return cases
}

// getEcosystem returns the Ecosystem for the given name, or skips the test.
func getEcosystem(t *testing.T, name string) interface {
	Parse(version string) (interface{ Compare(other interface{}) (int, error) }, error)
	IsSemver() bool
} {
	t.Helper()
	p := NewProvider(nil)
	eco, ok := p.Get(name)
	if !ok {
		t.Skipf("ecosystem %q not implemented", name)
		return nil
	}
	return eco
}

// ── File-based parity tests ───────────────────────────────────────────────────

func TestEcosystemParityFromFile(t *testing.T) {
	cases := loadParityCases(t)
	p := NewProvider(nil)

	for _, tc := range cases {
		tc := tc
		t.Run(tc.Ecosystem+"/"+tc.Input, func(t *testing.T) {
			eco, ok := p.Get(tc.Ecosystem)
			if !ok {
				t.Skipf("ecosystem %q not registered", tc.Ecosystem)
				return
			}
			_, err := eco.Parse(tc.Input)
			isValid := err == nil
			if isValid != tc.Valid {
				t.Errorf("Parse(%q) valid=%v, want %v (err=%v)", tc.Input, isValid, tc.Valid, err)
			}
		})
	}
}

func TestSortOrderParityFromFile(t *testing.T) {
	cases := loadParityCases(t)
	p := NewProvider(nil)

	for _, tc := range cases {
		if tc.InputA == "" || tc.InputB == "" {
			continue
		}
		tc := tc
		t.Run(tc.Ecosystem+"/sort/"+tc.InputA+"vs"+tc.InputB, func(t *testing.T) {
			eco, ok := p.Get(tc.Ecosystem)
			if !ok {
				t.Skipf("ecosystem %q not registered", tc.Ecosystem)
				return
			}
			vA, errA := eco.Parse(tc.InputA)
			if errA != nil {
				t.Skipf("cannot parse %q: %v", tc.InputA, errA)
				return
			}
			vB, errB := eco.Parse(tc.InputB)
			if errB != nil {
				t.Skipf("cannot parse %q: %v", tc.InputB, errB)
				return
			}
			cmp, err := vA.Compare(vB)
			if err != nil {
				t.Fatalf("Compare error: %v", err)
			}
			aBeforeB := cmp < 0
			if aBeforeB != tc.ABeforeB {
				t.Errorf("compare(%q, %q): got A<B=%v, want %v", tc.InputA, tc.InputB, aBeforeB, tc.ABeforeB)
			}
		})
	}
}

// ── Inline parity tests ───────────────────────────────────────────────────────

func TestPyPIVersionParity(t *testing.T) {
	p := NewProvider(nil)
	eco, ok := p.Get("PyPI")
	if !ok {
		t.Skip("PyPI ecosystem not available")
	}
	for _, v := range []string{"1.2.3", "1.2.3.post1", "1.2.3a1", "1.2.3rc1", "1.2.3.dev0", "0.0.1"} {
		if _, err := eco.Parse(v); err != nil {
			t.Errorf("PyPI.Parse(%q) unexpected error: %v", v, err)
		}
	}
}

func TestMavenSortParity(t *testing.T) {
	p := NewProvider(nil)
	eco, ok := p.Get("Maven")
	if !ok {
		t.Skip("Maven ecosystem not available")
	}
	cases := []struct {
		a, b   string
		aLessB bool
	}{
		{"1.0", "1.1", true},
		{"1.1", "2.0", true},
		{"2.0", "1.9", false},
		{"1.0.0", "1.0.1", true},
	}
	for _, tc := range cases {
		vA, errA := eco.Parse(tc.a)
		vB, errB := eco.Parse(tc.b)
		if errA != nil || errB != nil {
			t.Errorf("Maven.Parse errors: %v / %v", errA, errB)
			continue
		}
		cmp, err := vA.Compare(vB)
		if err != nil {
			t.Errorf("Maven.Compare(%q, %q): %v", tc.a, tc.b, err)
			continue
		}
		got := cmp < 0
		if got != tc.aLessB {
			t.Errorf("Maven sort(%q, %q): got A<B=%v, want %v", tc.a, tc.b, got, tc.aLessB)
		}
	}
}

func TestAlpineVersionParity(t *testing.T) {
	p := NewProvider(nil)
	eco, ok := p.Get("Alpine")
	if !ok {
		t.Skip("Alpine ecosystem not available")
	}
	for _, v := range []string{"1.2.3-r0", "1.2.3", "1.2.3_beta1-r0", "0.0.1-r1"} {
		if _, err := eco.Parse(v); err != nil {
			t.Errorf("Alpine.Parse(%q) unexpected error: %v", v, err)
		}
	}
}

func TestGoSemverParity(t *testing.T) {
	p := NewProvider(nil)
	eco, ok := p.Get("Go")
	if !ok {
		t.Skip("Go ecosystem not available")
	}
	if !eco.IsSemver() {
		t.Error("Go ecosystem should report IsSemver()=true")
	}
	for _, v := range []string{"1.21.0", "1.22.3", "0.18.0"} {
		if _, err := eco.Parse(v); err != nil {
			t.Errorf("Go.Parse(%q) unexpected error: %v", v, err)
		}
	}
}

func TestNPMSemverParity(t *testing.T) {
	p := NewProvider(nil)
	eco, ok := p.Get("npm")
	if !ok {
		t.Skip("npm ecosystem not available")
	}
	if !eco.IsSemver() {
		t.Error("npm ecosystem should report IsSemver()=true")
	}
	for _, v := range []string{"1.0.0", "2.3.4", "0.0.1-beta.1"} {
		if _, err := eco.Parse(v); err != nil {
			t.Errorf("npm.Parse(%q) unexpected error: %v", v, err)
		}
	}
}

func TestRPMVersionParity(t *testing.T) {
	// RPM used for RedHat, AlmaLinux, etc.
	p := NewProvider(nil)
	eco, ok := p.Get("AlmaLinux")
	if !ok {
		t.Skip("AlmaLinux/RPM ecosystem not available")
	}
	for _, v := range []string{"8.6-0.el8.1", "1.2.3-1.el8", "2.0.1-2.el9"} {
		if _, err := eco.Parse(v); err != nil {
			t.Errorf("RPM.Parse(%q) unexpected error: %v", v, err)
		}
	}
}
